### ISSUE TITLE
有考虑支持一下vue3+ts开发模式么

### ISSUE THREAD

**Issue by sqlyr** [Z-J-wang/render-jupyter-notebook-vue#80]
如题

**Comment by Z-J-wang** [comment]
你好！[render-juypter-notebook-vue](https://github.com/Z-J-wang/render-juypter-notebook-vue)可以在ts模式下直接引入使用的。

**Comment by sqlyr** [comment]
> 你好！[render-juypter-notebook-vue](https://github.com/Z-J-wang/render-juypter-notebook-vue)可以在vue3+ts模式下直接引入使用的。
> 
> ```ts
> <template>
>   <div class="home">
>     <RenderJupyterNotebook :notebook="notebook" />
>   </div>
> </template>
> 
> <script>
>   import RenderJupyterNotebook from 'render-jupyter-notebook-vue'; // vue 3.x 写法
>   import example from '../assets/OutputExamples.json';
> 
>   export default {
>     name: 'HomeView',
>     components: { RenderJupyterNotebook },
>     data() {
>       return {
>         notebook: example
>       };
>     }
>   };
> </script>
> ```
可以倒是可以，但是没有ts提示，需要自动手写，而且由于不了解实现，目前只能写成这样，除非主动看源码

/**
 * TODO 完善类型
 */
declare module 'render-jupyter-notebook-vue' {
  declare const RenderJupyterNotebookVue: any
  export default RenderJupyterNotebookVue
}

**Comment by Z-J-wang** [comment]
哦哦！明白你的诉求了。关于这部分有时间可以补上。

**Comment by Z-J-wang** [comment]
@sqlyr TypeScript 类型声明文件已经补充。更新到v2.2.2即可。

**Comment by sqlyr** [comment]
> @sqlyr TypeScript 类型声明文件已经补充。更新到v2.2.2即可。

![image](https://github.com/user-attachments/assets/485f6559-0678-4804-95b0-08e7236ee1fd)
单词拼错了，蚌埠住了(doge

**Comment by Z-J-wang** [comment]
> > @sqlyr TypeScript 类型声明文件已经补充。更新到v2.2.2即可。
> 
> ![image](https://private-user-images.githubusercontent.com/64026664/394075262-485f6559-0678-4804-95b0-08e7236ee1fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTg3MDcsIm5iZiI6MTczMzgxODQwNywicGF0aCI6Ii82NDAyNjY2NC8zOTQwNzUyNjItNDg1ZjY1NTktMDY3OC00ODA0LTk1YjAtMDhlNzIzNmVlMWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YmM2Yjc2ZTVjZTdhNGU0ZTc2N2E5Zjg4MGZjMmFjMGE2NzI4ZjRmZTA0Y2UxNzM2YWQ4MzM5YTI2NTM3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yyKxyFCfCK1_4Ikuget4xuf8eFXd_AmxroMHcMHV8Pg) 单词拼错了，蚌埠住了(doge

哈哈！是拼写错了。感谢反馈。已在v2.2.3版本修正。

**Comment by Z-J-wang** [comment]
#87
